apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/nguyenminhtiend/argo-cd-k8s.git
    targetRevision: main
    path: apps/nginx
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app
  
  syncPolicy:
    automated:
      prune: true        # Auto-delete resources when removed from git
      selfHeal: true     # Auto-revert manual changes
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true  # Auto-create namespace if missing
      - PruneLast=true        # Delete resources last during sync
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

