replicaCount: 1

image:
  repository: nginx
  tag: '1.27-alpine'
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

namespace: default

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  namespace: traefik
  match: ''
  stripPrefix: ''

resources:
  requests:
    memory: '64Mi'
    cpu: '100m'
  limits:
    memory: '128Mi'
    cpu: '200m'

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
