apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 31.1.1
    chart: traefik
    helm:
      releaseName: traefik
      values: |
        deployment:
          kind: Deployment
          replicas: 1

        service:
          type: ClusterIP

        ports:
          web:
            port: 80
            exposedPort: 80
          websecure:
            port: 443
            exposedPort: 443

        providers:
          kubernetesCRD:
            allowCrossNamespace: true

        ingressRoute:
          dashboard:
            enabled: false

        logs:
          general:
            level: INFO
          access:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
