apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice-common.fullname" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "microservice-common.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "microservice-common.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "microservice-common.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

