deployment:
  kind: Deployment
  replicas: 1

service:
  type: ClusterIP

ports:
  web:
    port: 80
    exposedPort: 80
  websecure:
    port: 443
    exposedPort: 443

providers:
  kubernetesCRD:
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: false

logs:
  general:
    level: INFO
  access:
    enabled: true
